# Numpy

In [2]:
import numpy as np

# Add()

In [3]:
np.add(3.4,5.6)

9.0

In [7]:
x1=np.arange(9.0).reshape((3,3))
x2=np.arange(3.0)
np.add(x1,x2)

array([[ 0.,  2.,  4.],
       [ 3.,  5.,  7.],
       [ 6.,  8., 10.]])

# Multiply()

In [8]:
a=np.array([2,3,5])
b=np.array([1,4,3])
results=np.multiply(a,b)

In [9]:
results

array([ 2, 12, 15])

# Split()

In [16]:
x1=np.array([1,2,3,4,5,6,7,8])
x2=np.array_split(x1,4)
print(x2)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]


# Join()

In [20]:
m=np.array([3,4,5])
n=np.array([6,7,8])
join=np.concatenate((m,n))
join

array([3, 4, 5, 6, 7, 8])

# Encode()

In [21]:
u=np.array(['AaAaAa', 'Ae', 'BabAaBaB'])
u

array(['AaAaAa', 'Ae', 'BabAaBaB'], dtype='<U8')

In [23]:
t=np.char.encode(u, encoding='cp037')
t

array([b'\xc1\x81\xc1\x81\xc1\x81', b'\xc1\x85',
       b'\xc2\x81\x82\xc1\x81\xc2\x81\xc2'], dtype='|S8')

In [24]:
v=np.char.decode(t, encoding='cp037')
v

array(['AaAaAa', 'Ae', 'BabAaBaB'], dtype='<U8')

# Function of Rounding

# numpy.arount()

In [25]:
h=np.array([2.0,-1.9,-3,4,8.9,2.1])
h

array([ 2. , -1.9, -3. ,  4. ,  8.9,  2.1])

In [26]:
np.around(h)

array([ 2., -2., -3.,  4.,  9.,  2.])

# numpy.floor()

In [27]:
h=np.array([2.0,-1.9,-3,4,8.9,2.1])
h

array([ 2. , -1.9, -3. ,  4. ,  8.9,  2.1])

In [28]:
np.floor(h)

array([ 2., -2., -3.,  4.,  8.,  2.])

# numpy.ceil()

In [29]:
h=np.array([2.0,-1.9,-3,4,8.9,2.1])
h

array([ 2. , -1.9, -3. ,  4. ,  8.9,  2.1])

In [30]:
np.ceil(h)

array([ 2., -1., -3.,  4.,  9.,  3.])

# numpy.round()

In [35]:
import numpy as np
np.round(568023934231.7,2)

568023934231.7

# numpy.rint()

In [36]:
h=np.array([2.0,-1.9,-3,4,8.9,2.1])
h

array([ 2. , -1.9, -3. ,  4. ,  8.9,  2.1])

In [37]:
np.rint(h)

array([ 2., -2., -3.,  4.,  9.,  2.])

# numpy.fix()

In [38]:
h=np.array([2.0,-1.9,-3,4,8.9,2.1])
h

array([ 2. , -1.9, -3. ,  4. ,  8.9,  2.1])

In [39]:
np.fix(h)

array([ 2., -1., -3.,  4.,  8.,  2.])

# numpy.trunc()

In [40]:
h=np.array([2.0,-1.9,-3,4,8.9,2.1])
h

array([ 2. , -1.9, -3. ,  4. ,  8.9,  2.1])

In [41]:
np.trunc(h)

array([ 2., -1., -3.,  4.,  8.,  2.])

# Arithmetical Operation

# numpy.reciprocal()

In [42]:
n1=np.arange(7)

In [43]:
n1

array([0, 1, 2, 3, 4, 5, 6])

In [47]:
np.reciprocal(n1)

C:\Users\Aamina\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in reciprocal
  """Entry point for launching an IPython kernel.
C:\Users\Aamina\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in reciprocal
  """Entry point for launching an IPython kernel.


array([-2147483648,           1,           0,           0,           0,
                 0,           0], dtype=int32)

In [48]:
np.reciprocal([1,2,2.2,3.3])

array([1.        , 0.5       , 0.45454545, 0.3030303 ])

# numpy.power()

In [49]:
np.power(n1,2)

array([ 0,  1,  4,  9, 16, 25, 36], dtype=int32)

# numpy.mod()

In [50]:
np.mod([2.3,4.5,7], 2)

array([0.3, 0.5, 1. ])

In [53]:
np.remainder([4,7],[8,9])

array([4, 7], dtype=int32)

# numpy.real()

In [55]:
z1=np.array([1+3j, 2+4j, 9+2j])
z1

array([1.+3.j, 2.+4.j, 9.+2.j])

In [56]:
np.real(z1)

array([1., 2., 9.])

# numpy.imag()

In [57]:
np.imag(z1)

array([3., 4., 2.])

# nump.conj()

In [58]:
v=np.array([9.3j])
v

array([0.+9.3j])

In [59]:
np.conjugate(v)

array([0.-9.3j])

# numpy.angle()

In [63]:
np.angle([3.2j,0.3j,-2.4j,-5.1j])

array([ 1.57079633,  1.57079633, -1.57079633, -1.57079633])

In [70]:
np.angle(1.1j, deg=True)

90.0

# numpy.positive()

In [71]:
np.positive(n1)

array([0, 1, 2, 3, 4, 5, 6])

In [72]:
np.negative(n1)

array([ 0, -1, -2, -3, -4, -5, -6])

# numpy.true_divide()

In [74]:
np.true_divide(n1,2)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. ])

# numpy.floor_divide()

In [75]:
np.floor_divide(n1,2)

array([0, 0, 1, 1, 2, 2, 3], dtype=int32)

# numpy.float_power()

In [76]:
np.float_power(n1,3)

array([  0.,   1.,   8.,  27.,  64., 125., 216.])

# numpy.fmod()

In [77]:
np.fmod(n1,3)

array([0, 1, 2, 0, 1, 2, 0], dtype=int32)

# numpy.modf()

In [80]:
np.modf([3.4,2.2])

(array([0.4, 0.2]), array([3., 2.]))

# numpy.divmod()

In [82]:
np.divmod(n1,2)

(array([0, 0, 1, 1, 2, 2, 3], dtype=int32),
 array([0, 1, 0, 1, 0, 1, 0], dtype=int32))

In [87]:
np.divmod(np.arange(5), 3)

(array([0, 0, 0, 1, 1], dtype=int32), array([0, 1, 2, 0, 1], dtype=int32))