# Statistical Function

# numpy.amin()

In [2]:
import numpy as np

In [4]:
a1=np.arange(4)

In [5]:
a1

array([0, 1, 2, 3])

In [6]:
a1=np.arange(4).reshape(2,2)

In [7]:
a1

array([[0, 1],
       [2, 3]])

In [8]:
np.amin(a1)

0

# numpy.ptp()

In [9]:
a2=np.array([[2,4,5,6], [5,1,8,8]])

In [10]:
a2

array([[2, 4, 5, 6],
       [5, 1, 8, 8]])

In [11]:
np.ptp(a2)

7

# numpy.percentile()

In [15]:
np.percentile(a2,100)

8.0

# numpy.median()

In [14]:
np.median(a2)

5.0

# numpy.mean()

In [16]:
np.mean(a2)

4.875

# numpy.average()

In [17]:
np.average(a2)

4.875

In [24]:
np.average(np.arange(1,11), weights=np.arange(10,0,-1))

4.0

# Sort, Search and Counting Function

# numpy.sort()

In [25]:
b1=np.arange(12).reshape(3,4)

In [26]:
b1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
np.sort(b1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
np.sort(b1, axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [33]:
np.sort(b1, axis=None)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

# numpy.argsort()

In [39]:
ind=np.argsort(b1)
ind

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]], dtype=int64)

# numpy.lexsort()

In [47]:
np.lexsort(b1)

array([0, 1, 2, 3], dtype=int64)

# numpy.nonzero()

In [48]:
np.nonzero(b1)

(array([0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2], dtype=int64),
 array([1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3], dtype=int64))

# numpy.where()

In [49]:
z=np.random.randn(2,3)

In [50]:
z

array([[-0.22510356, -0.35823903, -0.62915107],
       [ 3.64614237, -0.0493089 , -0.20031477]])

In [52]:
np.where(z>0, z, 0)

array([[0.        , 0.        , 0.        ],
       [3.64614237, 0.        , 0.        ]])

# numpy.extract()

In [56]:
array=np.arange(12).reshape(3,4)

In [57]:
array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [58]:
condition=np.mod(array, 3)==0

In [59]:
condition

array([[ True, False, False,  True],
       [False, False,  True, False],
       [False,  True, False, False]])

In [61]:
np.extract(condition, array)

array([0, 3, 6, 9])

# Sum, Product, Difference()

# numpy.prod()

In [72]:
r1=np.array([34523,56463])
r1

array([34523, 56463])

In [73]:
np.prod(r1)

1949272149

# numpy.sum()

In [75]:
np.sum(r1)

90986

# numpy.nanprod()

In [76]:
np.nanprod(r1)

1949272149

In [81]:
t=np.array([[1,2],[3, np.nan]])
t

array([[ 1.,  2.],
       [ 3., nan]])

In [82]:
np.nanprod(t)

6.0

# numpy.nansum()

In [87]:
w=np.array([[1,1], [1,np.nan]])
w

array([[ 1.,  1.],
       [ 1., nan]])

In [88]:
np.nansum(w)

3.0

# numpy.cumprod()

In [89]:
w1=np.array([[2,3], [4,np.nan]])
w1

array([[ 2.,  3.],
       [ 4., nan]])

In [91]:
np.cumprod(w1)

array([ 2.,  6., 24., nan])

# numpy.cumsum()

In [92]:
np.cumsum(w1)

array([ 2.,  5.,  9., nan])

# numpy.nancumprod()

In [93]:
y1=np.array([[4,5],[6,np.nan]])
y1

array([[ 4.,  5.],
       [ 6., nan]])

In [94]:
np.nancumprod(y1)

array([  4.,  20., 120., 120.])

# numpy.nancumsum()

In [96]:
np.nancumsum(y1)

array([ 4.,  9., 15., 15.])

# numpy.diff()

In [98]:
g1=np.array([4,5,6])
g1

array([4, 5, 6])

In [99]:
g2=np.array([8,9,2])
g2

array([8, 9, 2])

In [102]:
np.diff(g2-g1)

array([ 0, -8])

# numpy.ediff1d()

In [104]:
np.ediff1d(g1)

array([1, 1])

In [105]:
np.ediff1d(g2)

array([ 1, -7])

# numpy.gradient()

In [106]:
np.gradient(g1)

array([1., 1., 1.])

# numpy.cross()

In [109]:
x=[3,4,5]
y=[6,7,8]

In [110]:
x

[3, 4, 5]

In [111]:
y

[6, 7, 8]

In [112]:
np.cross(x,y)

array([-3,  6, -3])

# numpy.trapz()

In [114]:
np.trapz(x, y)

8.0

# Trignometric Function

# numpy.sin()

In [6]:
import numpy as np
import math
np.sin(np.pi/2)

1.0

# numpy.cos()

In [7]:
np.cos(np.array([0,np.pi/2,np.pi]))

array([ 1.000000e+00,  6.123234e-17, -1.000000e+00])

# numpy.tan()

In [10]:
np.tan(np.array([-pi, pi/2, pi]))

array([ 1.59265494e-03,  1.25576559e+03, -1.59265494e-03])

# numpy.arcsin()

In [11]:
np.arcsin(1)

1.5707963267948966

# numpy.arccos()

In [13]:
np.arccos([1,-1])

array([0.        , 3.14159265])

# numpy.arctan()

In [14]:
np.arctan([0,1])

array([0.        , 0.78539816])

# numpy.hypot()

In [16]:
np.hypot(3*np.ones((3,3)), 4*np.ones((3,3)))

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

# numpy.degrees()

In [18]:
rad=np.arange(12.)*np.pi/6
np.degrees(rad)

array([  0.,  30.,  60.,  90., 120., 150., 180., 210., 240., 270., 300.,
       330.])

# numpy.radian()

In [19]:
deg=np.arange(12.)*30

In [20]:
deg

array([  0.,  30.,  60.,  90., 120., 150., 180., 210., 240., 270., 300.,
       330.])

In [21]:
np.radians(deg)

array([0.        , 0.52359878, 1.04719755, 1.57079633, 2.0943951 ,
       2.61799388, 3.14159265, 3.66519143, 4.1887902 , 4.71238898,
       5.23598776, 5.75958653])

# numpy.unwrap()

In [22]:
phase=np.linspace(0,np.pi,num=5)
phase[3:]+=np.pi

In [23]:
phase

array([0.        , 0.78539816, 1.57079633, 5.49778714, 6.28318531])

In [25]:
np.unwrap(phase)

array([ 0.        ,  0.78539816,  1.57079633, -0.78539816,  0.        ])