# Pandas Library

In [1]:
import pandas as pd
df=pd.DataFrame({'A':['History', 'Maths', 'Zoology'],
                'B':[95,89,99],
                'C':['Amitha','Rahul','Jay'],
                'D':['Movies', 'Comedy','Horror']})

In [2]:
df

A   B       C       D
0  History  95  Amitha  Movies
1    Maths  89   Rahul  Comedy
2  Zoology  99     Jay  Horror

# Melt()

In [3]:
pd.melt(df, id_vars=['A'], value_vars=['B'])

A variable  value
0  History        B     95
1    Maths        B     89
2  Zoology        B     99

# pivot()

In [4]:
pd.pivot(df, index=['A'], columns='C',values='B')

C        Amitha   Jay  Rahul
A                           
History    95.0   NaN    NaN
Maths       NaN   NaN   89.0
Zoology     NaN  99.0    NaN

# Pivot_table()

In [5]:
import numpy as np
pd.pivot_table(df, index=['A','D'], columns=['C'], values=['B'], aggfunc=np.sum)

B            
C              Amitha   Jay Rahul
A       D                        
History Movies   95.0   NaN   NaN
Maths   Comedy    NaN   NaN  89.0
Zoology Horror    NaN  99.0   NaN

# cut()

In [6]:
c1=pd.cut(np.array([34,23,55,6,1]), 3)

In [7]:
c1

[(19.0, 37.0], (19.0, 37.0], (37.0, 55.0], (0.946, 19.0], (0.946, 19.0]]
Categories (3, interval[float64]): [(0.946, 19.0] < (19.0, 37.0] < (37.0, 55.0]]

# qcut()

In [8]:
q1=pd.qcut(range(5),4)

In [9]:
q1

[(-0.001, 1.0], (-0.001, 1.0], (1.0, 2.0], (2.0, 3.0], (3.0, 4.0]]
Categories (4, interval[float64]): [(-0.001, 1.0] < (1.0, 2.0] < (2.0, 3.0] < (3.0, 4.0]]

# crosstab()

In [10]:
a=np.array(["Rani","Badhusha","Maharaja","Salman"], dtype=object)
b=np.array(["Numbers", "Alphabets","Numeric","Symbols"], dtype=object)
c=np.array([1,2,3,4], dtype=object)

In [11]:
a

array(['Rani', 'Badhusha', 'Maharaja', 'Salman'], dtype=object)

In [12]:
b

array(['Numbers', 'Alphabets', 'Numeric', 'Symbols'], dtype=object)

In [13]:
c

array([1, 2, 3, 4], dtype=object)

In [14]:
pd.crosstab(a,[b,c], rownames='a',colnames=['b','c'])

b        Alphabets Numbers Numeric Symbols
c                2       1       3       4
a                                         
Badhusha         1       0       0       0
Maharaja         0       0       1       0
Rani             0       1       0       0
Salman           0       0       0       1

# merge()

In [15]:
df1=pd.DataFrame({'A':["Lavender","Purple","Rose","Red"],
                 'B':["AI", "ML", "NN", "DL"],
                 'C':[98,34,23,78]})

In [16]:
df1

A   B   C
0  Lavender  AI  98
1    Purple  ML  34
2      Rose  NN  23
3       Red  DL  78

In [17]:
df2=pd.DataFrame({'A':["Lavender","Purple","Rose","Red"],
                 'B':["Cricket", "FootBall", "Badmiton", "Hockey"],
                 'C':["Books", "Novels","Fairy tale", "Stories"]})

In [18]:
df2

A         B           C
0  Lavender   Cricket       Books
1    Purple  FootBall      Novels
2      Rose  Badmiton  Fairy tale
3       Red    Hockey     Stories

In [19]:
m=df1.merge(df2, left_on='A', right_on='B')

In [20]:
m

Empty DataFrame
Columns: [A_x, B_x, C_x, A_y, B_y, C_y]
Index: []

In [21]:
pd.merge(df1,df2, on='A')

A B_x  C_x       B_y         C_y
0  Lavender  AI   98   Cricket       Books
1    Purple  ML   34  FootBall      Novels
2      Rose  NN   23  Badmiton  Fairy tale
3       Red  DL   78    Hockey     Stories

# merge_ordered()

In [22]:
df3=pd.DataFrame({"keys":['a', 'b', 'c'], "org":['Kidney','Liver','Pancreas']})

In [23]:
df3

keys       org
0    a    Kidney
1    b     Liver
2    c  Pancreas

In [24]:
df4=pd.DataFrame({"keys":['a','b','e','m'], "sur":['water','sunlight','moon','sky']})

In [25]:
df4

keys       sur
0    a     water
1    b  sunlight
2    e      moon
3    m       sky

In [26]:
pd.merge_ordered(df3,df4, fill_method="ffill", left_by="keys")

keys       org       sur
0    a    Kidney     water
1    b     Liver  sunlight
2    c  Pancreas       NaN

# merge_asof()

In [27]:
m1=pd.DataFrame({"a":[1,2,3,4], "lvalues":["one", "two","three","four"]})

In [28]:
m1

a lvalues
0  1     one
1  2     two
2  3   three
3  4    four

In [29]:
m2=pd.DataFrame({"a":[1,3,5],"rvalues":["L1","L2","L3"]})

In [30]:
m2

a rvalues
0  1      L1
1  3      L2
2  5      L3

In [31]:
pd.merge_asof(m2, m1, on="a", direction="nearest" ) #right to left

a rvalues lvalues
0  1      L1     one
1  3      L2   three
2  5      L3    four

In [32]:
pd.merge_asof(m1,m2, on="a" ) #left to right

a lvalues rvalues
0  1     one      L1
1  2     two      L1
2  3   three      L2
3  4    four      L2

# Concat()

In [33]:
import pandas as pd
s1=pd.Series(['a','b','c', 'd'])
s2=pd.Series(['z','t','l','w'])

In [34]:
s1

0    a
1    b
2    c
3    d
dtype: object

In [35]:
s2

0    z
1    t
2    l
3    w
dtype: object

In [36]:
pd.concat([s1,s2])

0    a
1    b
2    c
3    d
0    z
1    t
2    l
3    w
dtype: object

# get_dummies()

In [37]:
s=pd.Series(list('abcd'))

In [39]:
s

0    a
1    b
2    c
3    d
dtype: object

In [38]:
pd.get_dummies(s)

a  b  c  d
0  1  0  0  0
1  0  1  0  0
2  0  0  1  0
3  0  0  0  1

# factorize()

In [40]:
codes, unique=pd.factorize(['b', 'c', 'b', 'a', 'a'])

In [41]:
codes

array([0, 1, 0, 2, 2], dtype=int64)

In [42]:
unique

array(['b', 'c', 'a'], dtype=object)

# unique()

In [44]:
u=pd.Series([1,3,2,3,3,4,5,6])

In [48]:
u

0    1
1    3
2    2
3    3
4    3
5    4
6    5
7    6
dtype: int64

In [49]:
pd.unique(u)

array([1, 3, 2, 4, 5, 6], dtype=int64)

# wide_to_long()

In [50]:
np.random.seed(123)

In [57]:
df=pd.DataFrame({"A1970": {0:"a", 1:"b", 2:"c"},
               "A1980":{0:"d",1:"e",2:"f"},
               "B1970":{0:2.5,1:3.4,2:5},
               "B1980":{0:.9,1:8.3,2:1.2},
                "X":dict(zip(range(3), np.random.rand(3)))})

df["id"]=df.index

In [58]:
df

A1970 A1980  B1970  B1980         X  id
0     a     d    2.5    0.9  0.551315   0
1     b     e    3.4    8.3  0.719469   1
2     c     f    5.0    1.2  0.423106   2

In [60]:
pd.wide_to_long(df, ["A","B"], i="id", j="Year")

X  A    B
id Year                  
0  1970  0.551315  a  2.5
1  1970  0.719469  b  3.4
2  1970  0.423106  c  5.0
0  1980  0.551315  d  0.9
1  1980  0.719469  e  8.3
2  1980  0.423106  f  1.2

# Top Level Missing data()

# isna()

In [62]:
array=np.array([[2, np.nan, 3],[5,2,np.nan]])

In [63]:
array

array([[ 2., nan,  3.],
       [ 5.,  2., nan]])

In [65]:
pd.isna(array)

array([[False,  True, False],
       [False, False,  True]])

# isnull()

In [66]:
dfs=pd.DataFrame([['bee', None, 'zoo'],['cat', 'lion', None]])

In [67]:
dfs

0     1     2
0  bee  None   zoo
1  cat  lion  None

In [68]:
pd.isnull(dfs)

0      1      2
0  False   True  False
1  False  False   True

# notna()

In [69]:
dfs1=pd.DataFrame([['ab', np.nan,90], [np.nan, 78, 'rts']])

In [70]:
dfs1

0     1    2
0   ab   NaN   90
1  NaN  78.0  rts

In [71]:
pd.notna(dfs1)

0      1     2
0   True  False  True
1  False   True  True

# Top Level Conversion

# to_numeric()

In [80]:
d1=pd.Series(['2', '-4',6])
d2=pd.Series(['3',1, '9'])

In [81]:
d1

0     2
1    -4
2     6
dtype: object

In [82]:
d2

0    3
1    1
2    9
dtype: object

In [83]:
pd.to_numeric(d1)

0    2
1   -4
2    6
dtype: int64

In [84]:
pd.to_numeric(d2, downcast='float')

0    3.0
1    1.0
2    9.0
dtype: float32

In [85]:
pd.to_numeric(d1, downcast='signed')

0    2
1   -4
2    6
dtype: int8

# Top level dealing with date time

# to_datetime()

In [86]:
dt=pd.DataFrame({"Year":[2020, 2021],
                "Month":[2,3],
                "Days":[22,28]})

In [87]:
dt

Year  Month  Days
0  2020      2    22
1  2021      3    28

In [88]:
pd.to_datetime(dt)

0   2020-02-22
1   2021-03-28
dtype: datetime64[ns]

# to_timedelta()

In [89]:
pd.to_timedelta('1 days 06:15:01.000042')

Timedelta('1 days 06:15:01.000042')

In [93]:
pd.to_timedelta('15.05us')

Timedelta('0 days 00:00:00.000015050')

# date_range()

In [94]:
pd.date_range(start='19/10/2021', end='25/10/2021')

DatetimeIndex(['2021-10-19', '2021-10-20', '2021-10-21', '2021-10-22',
               '2021-10-23', '2021-10-24', '2021-10-25'],
              dtype='datetime64[ns]', freq='D')

# period_range()

In [95]:
pd.period_range(start='2021-10-19', end='2021-10-30', freq='M')

PeriodIndex(['2021-10'], dtype='period[M]', freq='M')

# timedelta_range()

In [98]:
pd.timedelta_range(start='1 day', periods=5)

TimedeltaIndex(['1 days', '2 days', '3 days', '4 days', '5 days'], dtype='timedelta64[ns]', freq='D')

# Top dealing with Intervals

# interval_range()

In [99]:
pd.interval_range(start=0, end=5)

IntervalIndex([(0, 1], (1, 2], (2, 3], (3, 4], (4, 5]],
              closed='right',
              dtype='interval[int64]')

# Top level Evaluation

# eval()

In [100]:
e=pd.DataFrame({"animals": ["dog", "cat","horse"],
               "age":[10,30,40]})

In [101]:
e

animals  age
0     dog   10
1     cat   30
2   horse   40

In [102]:
pd.eval("double_age=e.age*2", target=e)

animals  age  double_age
0     dog   10          20
1     cat   30          60
2   horse   40          80